[env]
term = "alacritty"

[bell.command]
args = ["-e", "beep"]
program = "osascript"

# TokyoNight Alacritty Colors
[colors.primary]
background = '#24283b'
foreground = '#c0caf5'

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[cursor]
blink_interval = 500

[mouse]
hide_when_typing = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 17

[font.normal]
family = "Cascadia Mono NF"
style = "Light"

[font.bold]
family = "Cascadia Mono NF"
style = "SemiLight"

[font.bold_italic]
family = "Cascadia Mono NF"
style = "SemiLight Italic"

[font.italic]
family = "Cascadia Mono NF"
style = "Light Italic"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[window]
dynamic_padding = true
startup_mode = "Fullscreen"
